version: "2"

services:
  mrkunkel-resume:
    container_name: mrkunkel-resume
    image: mrkunkel/nginx_resume:latest
    restart: always
    expose:
      - "80"
    networks:
      - caddy_external_hrc51

networks:
  caddy_external_hrc51:
    external: true
